# Mathematical operations

In [1]:
from spectrochempy import *

<img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAAlw
 SFlzAAAJOgAACToB8GSSSgAAAetpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6
 bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8x
 OTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAg
 eG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMu
 YWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+bWF0cGxvdGxpYiB2ZXJzaW9uIDIuMS4wLCBo
 dHRwOi8vbWF0cGxvdGxpYi5vcmcvPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6
 T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgqNQaNYAAAGiUlE
 QVRIDY1We4xU1Rn/3XPuYx47u8w+hnU38hTcuoUEt/6D2y4RB0ME1BoEd9taJaKh9CFiN7YGp7appUAMNmktMZFoJTYVLVQ0smsy
 26CN0SU1QgsuFAaW3WVmx33N677O6XfuyoIxTXqSO/fec+75fd93vt/3/UbDV0aKSZmCpkFMLz3T9utuu2N+o98aDSMBKVAo89z5
 y+zEz3ZafcCOfvWdlGCalqKn1Bf71CygTd+mf1esSOnpdMpTb+vWpTZuWVfe3jLPa5tzHYNm0T5N0gpdkkHaDBeGBU6d1/t/fyS8
 +/CbqdfUvmsx1PuMgc2bNxv79u1zgd31r+7JH1jbIZKxWRXAcYUQ8IWvBfBXNjEuJWPgMA02NR7C3/pYT9fjdZ3A9tGrWF8YSJHn
 qcDz3y7q2T967PZv+gnYJdd1mEZ+62zGDQV/dQgKhmLzDNOXCEWM3j6eTT5Y3w78dOBKJLR1PQf+4ivPj76UPZnssBN+wbM9Aet/
 AV81Mf1EEULXYfOobvX2WWQk0aoioXwwSmirOlioY0mu8BIouzYl7P8GV3vpqCCEZvlFz769w08oLDWvyKIyL1asSm28d6WfzA97
 ztvvV1kexUMsmhlkULEkuGYmFYC6AvfUrITnwUKl5K79lkjeSSRRTCTbQPd95e1WzMbZSya74XoXAxctCllCnbECMOjZNGRwvzIX
 nD85wbkMmKK+U045Dtdi8Qp+SAxU2GTg2bYlC9224pgvmSb54vkVTBQYyhUt2KjAMyMmPjwRQW5Mh2WKwJhlBh6jVGagFM84wZnQ
 4bpC0Rt4pk1PbSt0NDcxDA5xryosDHWgtbM0DGZDWLSoiDMDYeQnGVrmOThxLozB0RAaahzkJzjKNqcIQBymJFMkOlN8Dqjpg0XY
 Tx5xO/QbmmUrqIjGJznq47TqTaClKYfjp+PInLMwnOdYvtQBZ2XcunQY+VwIo4U4muoFEjVEFE6lQyEUKzHYfgQG9ylCyngU+Cxj
 tOqxCDGHcCsOMCs6iQul5ZiStdATYxjMZXDLTUVwLY8Jey4uOh2IxjwsrP8UXJYxUrkZrghBahzV5iXU6gNkq0Z1EzIsUBUSCV2n
 EOHo0LVxHCpuxabJJdhi5PFnvw5vLXwXIfNZvD/+JNo/X40NegE54sUaazl+UL8XD1x+FB9Ijjt4EQfdGN6J/x131LwIV9ap/AYs
 0x1fz1ZKFbh6A7qKy/By9Dg6G36Ep91vUJJ15Cqr0Z67E8/HzmBrw1OwxWyM+3Mo6BAuSB17oyfx0Oyl2DN0Hqs/70Cx6hBCvESF
 UY1ShWXZZEE7OTAYxZzaPH4TuoiusZvRnunFy2NbiHYuBp2vB66srX4vMEjpRKPxKXmnoQ4+Mn4DPiv8CYcrs3GfNUXJLtM+alSO
 hrMj/KT+wBNW3+E/2liywNO3iSflbaFva/+stGDTxE0E9Sjaox8HBhxpEamzMGSEaFKg+mjEddzDh1MxTDq3YV1kGBsjfwW3S9Cq
 anjmko+ndlb1UR3s6K8JlfphNWq9Ew/7c61T2BB/EbcaNkb8GBaE0tANH7/M34PLdhJDzjIcL9xPbdTG6zyM72Y+wXPHmvB489No
 fm0b5HnbQ9Rgp/7DSSd29AeVvPeNyK6JcYl/yQVi5dBjuGvoV/gaJe47s45QUxrDmcYX0MBsdF7egvXZ7+O0vZA4X8QmOQWjlSK7
 RDz5wIM30gp9UbWcGjXxhzdDu1SiNSpx6kcQB57rPnr/3dlkZarWLnlRq5oPET1dOCIOk4wALib9eeS5iygfhkd09H0DWphB/+gs
 +PcOAS+ssrFmmXXgVfR0de9cpbAJfH3Q1jofW9DZk56dDcVsq9YcsoUMEd1qyLoT3BX1YiyHMJuk97hyjqIoE91t+NcTLeN0ZrfM
 oXatZbu6G0h4VG+ibqq0IJVK6cAjo6serG3vSUezCMct0yQeSOFJSUImqb2qbknUpDqlZxE0QZ+ZUpSlZx79h4Nda6zef9dlk121
 JDjbR5XggPRZlRnS6bRQRtLpn4++cuie/Yvn2svmNxuLw9WCcYIl4fEoTEGiSTUqJdfgU+8ROqf1iMkLzS389YtNPXc/PH8l8ONB
 JZkHD+4JtD04HmVEDWWErmBhzV2/2LB1bemJG6krzv2S6NOHUgtEP0Oif5pE/3fHoruP7N8RiP61GArzSwbUhJJQpXJKiKbfr/3b
 IhKq76sKPUdF9NW/LSqfSn6vjv8C45H/6FSgvZQAAAAASUVORK5CYII='
 style='height:25px; border-radius:12px; display:inline-block; float:left; vertical-align:middle'> 
 
 
 
    SpectroChemPy's API - v.0.1a14.dev91+g4fa73cc.d20200415 © Copyright 2014-2020 - A.Travert & C.Fernandez @ LCS

## Ufuncs (Universal Numpy's functions)
A universal function (or `ufunc` in short) is a function that operates on numpy arrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a `ufunc` is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

For instance, in numpy to calculate the square root of each element of a given nd-array, we can write something like this using the `np.sqrt` functions :

In [2]:
x = np.array([1.,2.,3.,4.,6.])
np.sqrt(x)

array([       1,    1.414,    1.732,        2,    2.449])

As seen above, `np.sqrt(x)` return a numpy array.

The interesting thing, it that `ufunc`'s can also work with `NDDataset`.

In [3]:
dx = NDDataset(x)
np.sqrt(dx)

NDDataset: [float64] unitless (size: 5)

In this case a `NDDataset` object is returned.

A subset of `ufunc`'s also work works with `NDPanel`. Ufunc is then broadcasted to all internal arrays.

In [4]:
x = np.arange(6.)
y = np.arange(8.)
pnl = NDPanel(x, y)
np.sqrt(pnl)

NDPanel: (size: 2 datasets)

As observed in the example above, in this case a `NDPanel`is returned on which each internal datasets have been transformed by the `ufunc`.

It is worth to note, that in spectrochempy, when can use internal equivalent of these `ufunc`'s.

For instance, the square root can be calculated using the following syntax:

In [5]:
import spectrochempy as scp 
scp.sqrt(dx)

NDDataset: [float64] unitless (size: 5)

or

In [6]:
from spectrochempy import *
sqrt(dx)

NDDataset: [float64] unitless (size: 5)

## List of UFuncs working on `NDDataset`:

if an Ufunc works on `NDDataset` but not on `NDPanel`, this is specified in the list below.

### Functions affecting magnitudes of the number but keeping units
* [negative](#negative)(x, \*\*kwargs): Numerical negative, element-wise. 
* [absolute](#abs)(x, \*\*kwargs): Calculate the absolute value, element-wise. Alias: [abs](#abs)
* [fabs](#abs)(x, \*\*kwargs): Calculate the absolute value, element-wise. Complex values are not handled, use [absolute](#absolute) to find the absolute values of complex data.
* [conj](#)(x, \*\*kwargs): Return the complex conjugate, element-wise. 
* [rint](#rint)(x, \*\*kwargs) :Round to the nearest integer, element-wise.  
* [floor](#floor)(x, \*\*kwargs): Return the floor of the input, element-wise.
* [ceil](#ceil)(x, \*\*kwargs): Return the ceiling of the input, element-wise.
* [trunc](#trunc)(x, \*\*kwargs): Return the truncated value of the input, element-wise. 

### Functions affecting magnitudes of the number but also units
* [sqrt](#sqrt)(x, \*\*kwargs): Return the non-negative square-root of an array, element-wise.
* [square](#square)(x, \*\*kwargs): Return the element-wise square of the input.
* [cbrt](#cbrt)(x, \*\*kwargs): Return the cube-root of an array, element-wise.
* [reciprocal](#reciprocal)(x, \*\*kwargs): Return the reciprocal of the argument, element-wise.

### Functions that require no units or dimensionless units for inputs. Returns dimensionless objects.
* [exp](#exp)(x, \*\*kwargs): Calculate the exponential of all elements in the input array.
* [exp2](#exp)(x, \*\*kwargs): Calculate 2\*\*p for all p in the input array.
* [expm1](#exp)(x, \*\*kwargs): Calculate `exp(x) - 1` for all elements in the array. 
* [log](#log)(x, \*\*kwargs): Natural logarithm, element-wise. 
* [log2](#log)(x, \*\*kwargs): Base-2 logarithm of x.
* [log10](#log)(x, \*\*kwargs): Return the base 10 logarithm of the input array, element-wise. 
* [log1p](#log)(x, \*\*kwargs): Return `log(x + 1)`, element-wise.

### Functions that return numpy arrays (*Work only for NDDataset*)
* [sign](#sign)(x): Returns an element-wise indication of the sign of a number.
* [logical_not](#logical_not)(x): Compute the truth value of NOT x element-wise. 
* [isfinite](#isfinite)(x): Test element-wise for finiteness.
* [isinf](#isinf)(x): Test element-wise for positive or negative infinity.
* [isnan](#isnan)(x): Test element-wise for `NaN` and return result as a boolean array.
* [signbit](#signbit)(x): Returns element-wise `True` where signbit is set.

### Trigonometric functions. Require unitless data or radian units.
* [sin](#sin)(x, \*\*kwargs): Trigonometric sine, element-wise.
* [cos](#cos)(x, \*\*kwargs): Trigonometric cosine element-wise.
* [tan](#tan)(x, \*\*kwargs): Compute tangent element-wise. 

* [arcsin](#arcsin)(x, \*\*kwargs): Inverse sine, element-wise.
* [arccos](#arccos)(x, \*\*kwargs): Trigonometric inverse cosine, element-wise.
* [arctan](#arctan)(x, \*\*kwargs): Trigonometric inverse tangent, element-wise.

### Hyperbolic functions
* [sinh](#sinh)(x, \*\*kwargs): Hyperbolic sine, element-wise.
* [cosh](#cosh)(x, \*\*kwargs): Hyperbolic cosine, element-wise.
* [tanh](#tanh)(x, \*\*kwargs): Compute hyperbolic tangent element-wise.
* [arcsinh](#arcsinh)(x, \*\*kwargs): Inverse hyperbolic sine element-wise.
* [arccosh](#arccosh)(x, \*\*kwargs): Inverse hyperbolic cosine, element-wise.
* [arctanh](#arctanh)(x, \*\*kwargs): Inverse hyperbolic tangent element-wise.

### Unit conversions
* [deg2rad](#deg2rad)(x, \*\*kwargs): Convert angles from degrees to radians.
* [rad2deg](#rad2deg)(x, \*\*kwargs): Convert angles from radians to degrees.

### Binary Ufuncs

* [add](#add)(x1, x2, \*\*kwargs): Add arguments élement-wise.
* [subtract](#subtract)(x1, x2, \*\*kwargs): Subtract arguments, element-wise.
* [multiply](#multiply)(x1, x2, \*\*kwargs): Multiply arguments element-wise.
* [divide](#divide) or [true_divide](#true_divide)(x1, x2, \*\*kwargs): Returns a true division of the inputs, element-wise.
* [floor_divide](#floor_divide)(x1, x2, \*\*kwargs): Return the largest integer smaller or equal to the division of the inputs.
* [mod](#mod) or [remainder](#remainder)(x1, x2,\*\*kwargs): Return element-wise remainder of division.
* [fmod](#fmod)(x1, x2, \*\*kwargs): Return the element-wise remainder of division. 
* [logaddexp](#logaddexp)(x1, x2,\*\*kwargs): Logarithm of the sum of exponentiations of the inputs.
* [logaddexp2](#logaddexp2)(x1, x2, \*\*kwargs): Logarithm of the sum of exponentiations of the inputs in base-2.
* [heaviside](#heaviside)(x1, x2, \*\*kwargs): Compute the Heaviside step function.



## Usage
To demonstrate the use of mathematical operations on spectrochempy object, we will first load an experimental 2D dataset.

In [7]:
# import a dataset to check the ufuncs
dataset = NDDataset.read_omnic(os.path.join('irdata', 'NH4Y-activation.SPG'))
dataset

NDDataset: [float32] a.u. (shape: (y:55, x:5549))

This dataset will be artificially modified already using some mathematical operation (subtraction with a scalar) to present negative values.

In [8]:
dataset = dataset - 2.     # add an offset to make that some of the values become negative
dataset

NDDataset: [float32] a.u. (shape: (y:55, x:5549))

In [9]:
dataset = dataset.clip(1.8)  # additionally limit the upper values using the clip 
dataset

NDDataset: [float32] a.u. (shape: (y:55, x:5549))

In [10]:
_ = dataset.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Unary functions

#### Functions affecting magnitudes of the number but keeping units

##### negative
Numerical negative, element-wise, keep units

In [11]:
out = np.negative(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### abs
##### absolute (alias of abs)
##### fabs (absolute for float arrays)
Numerical absolute value element-wise, element-wise, keep units

In [12]:
out = np.abs(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### rint
Round elements of the array to the nearest integer, element-wise, keep units

In [13]:
out = np.rint(dataset)
_ = out.plot(figsize=(6,2.5))  # not that title is not modified for this ufunc

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### floor
Return the floor of the input, element-wise.

In [14]:
out = np.floor(dataset)
_ = out.plot(figsize=(6,2.5)) 

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### ceil
Return the ceiling of the input, element-wise.

In [15]:
out = np.ceil(dataset)
_ = out.plot(figsize=(6,2.5)) 

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### trunc
Return the truncated value of the input, element-wise.

In [16]:
out = np.trunc(dataset)
_ = out.plot(figsize=(6,2.5)) 

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Functions affecting magnitudes of the number but also units
##### sqrt
Return the non-negative square-root of an array, element-wise.

In [17]:
out = np.sqrt(dataset)   # as they are some negative elements, return dataset has complex dtype.
_ = out.real.plot(figsize=(6,2.5))
_ = out.imag.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### square
Return the element-wise square of the input.

In [18]:
out = np.square(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### cbrt
Return the cube-root of an array, element-wise.

In [19]:
out = np.cbrt(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### reciprocal
Return the reciprocal of the argument, element-wise.

In [20]:
out = np.reciprocal(dataset+3.)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Functions that require no units or dimensionless units for inputs. Returns dimensionless objects.

##### exp
Exponential of all elements in the input array, element-wise

In [21]:
out = np.exp(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Obviously numpy exponential functions applies only to dimensionless array. Else an error is generated.

In [22]:
x = NDDataset(np.arange(5), units='m')
try:
    np.exp(x)  # A dimensionality error will be generated
except DimensionalityError as e:
    #error_(e)
    print('Dimensionality error issued!')

Dimensionality error issued!


##### exp2
Calculate 2\*\*p for all p in the input array.

In [23]:
out = np.exp2(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### expm1 
Calculate `exp(x) - 1` for all elements in the array. 

In [24]:
out = np.expm1(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### log
Natural logarithm, element-wise. 

In [25]:
out = np.log(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### log2
Base-2 logarithm of x.

In [26]:
out = np.log2(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### log10
Return the base 10 logarithm of the input array, element-wise. 

In [27]:
out = np.log10(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### log1p
Return `log(x + 1)`, element-wise.

In [28]:
out = np.log1p(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Functions that return numpy arrays (*Work only for NDDataset*)

##### sign
Returns an element-wise indication of the sign of a number. Returned object is a ndarray

In [29]:
np.sign(dataset)

array([[       1,        1, ...,        1,        1],
       [       1,        1, ...,       -1,       -1],
       ...,
       [      -1,       -1, ...,       -1,       -1],
       [      -1,       -1, ...,       -1,       -1]], dtype=float32)

In [30]:
np.logical_not(dataset<0)

NDDataset: [bool] unitless (shape: (y:55, x:5549))

##### isfinite
Test element-wise for finiteness.

In [31]:
np.isfinite(dataset)

array([[  True,   True, ...,   True,   True],
       [  True,   True, ...,   True,   True],
       ...,
       [  True,   True, ...,   True,   True],
       [  True,   True, ...,   True,   True]])

##### isinf
Test element-wise for positive or negative infinity.

In [32]:
np.isinf(dataset)

array([[  False,   False, ...,   False,   False],
       [  False,   False, ...,   False,   False],
       ...,
       [  False,   False, ...,   False,   False],
       [  False,   False, ...,   False,   False]])

##### isnan
Test element-wise for `NaN` and return result as a boolean array.

In [33]:
np.isnan(dataset)

array([[  False,   False, ...,   False,   False],
       [  False,   False, ...,   False,   False],
       ...,
       [  False,   False, ...,   False,   False],
       [  False,   False, ...,   False,   False]])

##### signbit
Returns element-wise `True` where signbit is set.

In [34]:
np.signbit(dataset)

array([[  False,   False, ...,   False,   False],
       [  False,   False, ...,   True,   True],
       ...,
       [  True,   True, ...,   True,   True],
       [  True,   True, ...,   True,   True]])

#### Trigonometric functions. Require unitless dataset or radians.

##### sin
Trigonometric sine, element-wise.

In [35]:
out = np.sin(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### cos
Trigonometric cosine element-wise.

In [36]:
out = np.cos(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### tan
Compute tangent element-wise.

In [37]:
out = np.tan(dataset/np.max(dataset))
_ = out.plot(figsize=(6,2.5))

[SpectroChemPy] ERROR | ValueError: coordinate's sizes do not match


##### arcsin
Inverse sine, element-wise.

In [38]:
out = np.arcsin(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### arccos
Trigonometric inverse cosine, element-wise.

In [39]:
out = np.arccos(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### arctan
Trigonometric inverse tangent, element-wise.

In [40]:
out = np.arctan(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### arctan2
Element-wise arc tangent of x1/x2 choosing the quadrant correctly.

The quadrant (i.e., branch) is chosen so that arctan2(x1, x2) is the signed angle in radians between the ray ending at the origin and passing through the point (1,0), and the ray ending at the origin and passing through the point (x2, x1). 

In [41]:
out = np.arctan2(dataset, dataset*2.)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Angle units conversion

##### rad2deg
Convert angles from radians to degrees (warning: unitless or dimensionless are assumed to be radians, so no error will be issued).

for instance, if we take the z axis (the data magintude) in the figure above, it's expressed in radians. We can change to degrees easily.

In [42]:
out = np.rad2deg(dataset)
out.title = 'data' # just to avoid a too long title
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [47]:
pi = NDDataset(Quantity(np.pi,'dimensionless'))
np.sin(pi).data, np.sin(np.rad2deg(pi)).data

(array(1.225e-16), array( -0.8012))

##### deg2rad
Convert angles from degrees to radians.

In [48]:
out = np.deg2rad(out)
out.title = 'data' 
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Hyperbolic functions

##### sinh
Hyperbolic sine, element-wise.

In [49]:
out = np.sinh(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### cosh
Hyperbolic cosine, element-wise.

In [50]:
out = np.cosh(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### tanh
Compute hyperbolic tangent element-wise.

In [51]:
out = np.tanh(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### arcsinh
Inverse hyperbolic sine element-wise.

In [52]:
out = np.arcsinh(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### arccosh
Inverse hyperbolic cosine, element-wise.

##### arctanh
Inverse hyperbolic tangent element-wise.

In [53]:
out = np.arctanh(dataset)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Binary functions

In [54]:
dataset2 = np.exp(dataset)  # create a second dataset
_ = dataset.plot(figsize=(6,2.5))
_ = dataset2.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Arithmetics

##### add
Add arguments element-wise.

In [55]:
out = np.add(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### subtract
Subtract arguments, element-wise.

In [56]:
out = np.subtract(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### multiply
Multiply arguments element-wise.

In [57]:
out = np.multiply(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### divide
or
##### true_divide
Returns a true division of the inputs, element-wise.

In [58]:
out = np.divide(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### floor_divide
Return the largest integer smaller or equal to the division of the inputs.

In [59]:
out = np.floor_divide(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### mod
or
##### remainder
Return element-wise remainder of division.

In [60]:
out = np.mod(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### fmod
Return element-wise remainder of division.

**Note**: For `fmod`, the sign of result is the sign of the dividend, while for remainder the sign of the result is the sign of the divisor.

In [61]:
out = np.fmod(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### logaddexp
Logarithm of the sum of exponentiations of the inputs.
##### logaddexp2
Logarithm of the sum of exponentiations of the inputs in base-2.

In [62]:
out = np.logaddexp2(dataset, dataset2)
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

##### heaviside
Compute the Heaviside step function.

```
                      0   if x1 < 0
heaviside(x1, x2) =  x2   if x1 == 0
                      1   if x1 > 0
```

In [63]:
h = np.heaviside(dataset, dataset2)
_ = h.plot(figsize=(6,2.5))
out = dataset * h
_ = out.plot(figsize=(6,2.5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Logical and comparison operations

##### logical_not
Compute the truth value of NOT x element-wise. 

In [64]:
np.logical_not(dataset)

NDDataset: [bool] (shape: (y:55, x:5549))