# Overview

## Getting Started


### Using Jupyter Notebook

Assuming Jupyter is installed (*i.e.*, you have followed the [Spectrochempy installation procedure](../../../gettingstarted/install)), go to the
|scpy| folder. From this location, open a
terminal and type something like:

![launch](../images/launch_jupyter.png)

Your default explorer is now launched.

![launched](../images/jupyter_home.png)

You can now navigate to the Tutorial notebooks in [tutorial]  or the notebooks used for this user guide.

Click on the the fist notebook : **introduction.ipynb**

![introd](../images/jupyter_intro.png)

### Using Jupyter Lab

### Loading the API

<div class="alert alert-info">

**Note:** We assume the spectrochemistry package has been properly installed - if not please go to ``install``

</div>

Before using the package, we need to load the **API (Application Programming Interface)**

The simplest way is to import all the objects and methods at once into your python namespace.

In [1]:
from spectrochempy import *

<img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAAlw
 SFlzAAAJOgAACToB8GSSSgAAAetpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6
 bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8x
 OTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAg
 eG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMu
 YWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+bWF0cGxvdGxpYiB2ZXJzaW9uIDIuMS4wLCBo
 dHRwOi8vbWF0cGxvdGxpYi5vcmcvPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6
 T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgqNQaNYAAAGiUlE
 QVRIDY1We4xU1Rn/3XPuYx47u8w+hnU38hTcuoUEt/6D2y4RB0ME1BoEd9taJaKh9CFiN7YGp7appUAMNmktMZFoJTYVLVQ0smsy
 26CN0SU1QgsuFAaW3WVmx33N677O6XfuyoIxTXqSO/fec+75fd93vt/3/UbDV0aKSZmCpkFMLz3T9utuu2N+o98aDSMBKVAo89z5
 y+zEz3ZafcCOfvWdlGCalqKn1Bf71CygTd+mf1esSOnpdMpTb+vWpTZuWVfe3jLPa5tzHYNm0T5N0gpdkkHaDBeGBU6d1/t/fyS8
 +/CbqdfUvmsx1PuMgc2bNxv79u1zgd31r+7JH1jbIZKxWRXAcYUQ8IWvBfBXNjEuJWPgMA02NR7C3/pYT9fjdZ3A9tGrWF8YSJHn
 qcDz3y7q2T967PZv+gnYJdd1mEZ+62zGDQV/dQgKhmLzDNOXCEWM3j6eTT5Y3w78dOBKJLR1PQf+4ivPj76UPZnssBN+wbM9Aet/
 AV81Mf1EEULXYfOobvX2WWQk0aoioXwwSmirOlioY0mu8BIouzYl7P8GV3vpqCCEZvlFz769w08oLDWvyKIyL1asSm28d6WfzA97
 ztvvV1kexUMsmhlkULEkuGYmFYC6AvfUrITnwUKl5K79lkjeSSRRTCTbQPd95e1WzMbZSya74XoXAxctCllCnbECMOjZNGRwvzIX
 nD85wbkMmKK+U045Dtdi8Qp+SAxU2GTg2bYlC9224pgvmSb54vkVTBQYyhUt2KjAMyMmPjwRQW5Mh2WKwJhlBh6jVGagFM84wZnQ
 4bpC0Rt4pk1PbSt0NDcxDA5xryosDHWgtbM0DGZDWLSoiDMDYeQnGVrmOThxLozB0RAaahzkJzjKNqcIQBymJFMkOlN8Dqjpg0XY
 Tx5xO/QbmmUrqIjGJznq47TqTaClKYfjp+PInLMwnOdYvtQBZ2XcunQY+VwIo4U4muoFEjVEFE6lQyEUKzHYfgQG9ylCyngU+Cxj
 tOqxCDGHcCsOMCs6iQul5ZiStdATYxjMZXDLTUVwLY8Jey4uOh2IxjwsrP8UXJYxUrkZrghBahzV5iXU6gNkq0Z1EzIsUBUSCV2n
 EOHo0LVxHCpuxabJJdhi5PFnvw5vLXwXIfNZvD/+JNo/X40NegE54sUaazl+UL8XD1x+FB9Ijjt4EQfdGN6J/x131LwIV9ap/AYs
 0x1fz1ZKFbh6A7qKy/By9Dg6G36Ep91vUJJ15Cqr0Z67E8/HzmBrw1OwxWyM+3Mo6BAuSB17oyfx0Oyl2DN0Hqs/70Cx6hBCvESF
 UY1ShWXZZEE7OTAYxZzaPH4TuoiusZvRnunFy2NbiHYuBp2vB66srX4vMEjpRKPxKXmnoQ4+Mn4DPiv8CYcrs3GfNUXJLtM+alSO
 hrMj/KT+wBNW3+E/2liywNO3iSflbaFva/+stGDTxE0E9Sjaox8HBhxpEamzMGSEaFKg+mjEddzDh1MxTDq3YV1kGBsjfwW3S9Cq
 anjmko+ndlb1UR3s6K8JlfphNWq9Ew/7c61T2BB/EbcaNkb8GBaE0tANH7/M34PLdhJDzjIcL9xPbdTG6zyM72Y+wXPHmvB489No
 fm0b5HnbQ9Rgp/7DSSd29AeVvPeNyK6JcYl/yQVi5dBjuGvoV/gaJe47s45QUxrDmcYX0MBsdF7egvXZ7+O0vZA4X8QmOQWjlSK7
 RDz5wIM30gp9UbWcGjXxhzdDu1SiNSpx6kcQB57rPnr/3dlkZarWLnlRq5oPET1dOCIOk4wALib9eeS5iygfhkd09H0DWphB/+gs
 +PcOAS+ssrFmmXXgVfR0de9cpbAJfH3Q1jofW9DZk56dDcVsq9YcsoUMEd1qyLoT3BX1YiyHMJuk97hyjqIoE91t+NcTLeN0ZrfM
 oXatZbu6G0h4VG+ibqq0IJVK6cAjo6serG3vSUezCMct0yQeSOFJSUImqb2qbknUpDqlZxE0QZ+ZUpSlZx79h4Nda6zef9dlk121
 JDjbR5XggPRZlRnS6bRQRtLpn4++cuie/Yvn2svmNxuLw9WCcYIl4fEoTEGiSTUqJdfgU+8ROqf1iMkLzS389YtNPXc/PH8l8ONB
 JZkHD+4JtD04HmVEDWWErmBhzV2/2LB1bemJG6krzv2S6NOHUgtEP0Oif5pE/3fHoruP7N8RiP61GArzSwbUhJJQpXJKiKbfr/3b
 IhKq76sKPUdF9NW/LSqfSn6vjv8C45H/6FSgvZQAAAAASUVORK5CYII='
 style='height:25px; border-radius:12px; display: inline-block; float: left; vertical-align: middle'> 
 
 
 
    SpectroChemPy's API - v.0.1a9.dev12+gc24f2c04.d20190118 © Copyright 2014-2019 - A.Travert & C.Fernandez @ LCS

but you can also import method only when it is needed.

For instances, one object very usefull in the following will be a nd-dataset to contain some data. Instead of issuing the previous command, one can do:

In [2]:
from spectrochempy import NDDataset
mydataset = NDDataset()

In the second line we have defined a new empty instance of **NDDataset**, wich will be further use to load our data.

Another way to proceed is to not mix the API namespace with your normal python. 

In this case, you can simply do:


In [3]:
import spectrochempy as sc
mydataset = sc.NDDataset()

As such, the above command ``from spectrochempy import *``, lead to import of several objects and methods in the namespace.

To get a list of all available methods or objects, type the following command (*remove the leading #, first*):

In [4]:
# APIref

If something goes wrong with during a cell execution,  a ``traceback`` is displayed.

For instance, the object or method ``toto`` does not exist in the API, so an error (**ImportError**) is generated when trying to import this from the API. Here we catch the error with a try except structure

In [5]:
try:
    from spectrochempy import toto
except ImportError as e:
    log.error("OOPS, THAT'S AN IMPORT ERROR! : %s"%e)

[SpectroChemPy] ERROR | OOPS, THAT'S AN IMPORT ERROR! : cannot import name 'toto' from 'spectrochempy' (/Users/spectrocat/Dropbox/spectrochempy/spectrochempy/__init__.py)


The error will stop the execution if not catched.

This is a basic behavior of python : on way to avoid. stoppping the execution without displaying a message is :

In [6]:
try:
    from spectrochempy import toto
except:
    pass

### Configuration

Many options of the API can be set up

In [7]:
set_loglevel(INFO)

In the above cell, we have set the **log** level to display ``info`` messages, such as this one:

In [8]:
log.info('this is an info message!')
log.debug('this is a debug message!')

this is an info message!


Only the info message is displayed, as expected.

If we change it to ``DEBUG``, we should get the two messages

In [9]:
set_loglevel(DEBUG)

log.info('this is an info message!')
log.debug('this is a debug message!')

[application.py-_log_level_changed DEBUG] changed default log_level to DEBUG
[<ipython-input-9-ef0a7a37be7a>-<module> INFO] this is an info message!
[<ipython-input-9-ef0a7a37be7a>-<module> DEBUG] this is a debug message!


Let's now come back to a standard level of message for the rest of the Tutorial.

In [10]:
set_loglevel(WARNING)

log.info('this is an info message!')
log.debug('this is a debug message!')
log.warning('this is a warning message!')

this is a warning message!


### Access to scientific libraries

Several libraries are imported with **SpectroChemPy** (so you don't need to re-import them):

- **np** :  This is actually the **`numpy`** library, to perform numerical calculation on nD arrays. 
- **plt** : This is the **`matplotlib`** library, to allow plotting data 

Optionally, **scipy** and **sympy** can be available, if **SpectroChempy** can find these libraries installed on your system.

In [11]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
plt.figure(figsize=(5,2.5))
p, = plt.plot(x,y)
p.set_linewidth(2)
p.set_color('red')
plt.show()

FigureCanvasNbAgg()

### Units, uncertainties and measurements

The objets **ur**, **Quantity** and **Measurement**, allows the manipulation of data with units and uncertainties. (see tutorial-1-units-uncertainties)

* **ur**: the unit registry
* **Quantity**: a scalar or an array with some units
* **Measurement**: a scalar with units and unertainty

In [12]:
ur.cm / ur.s

<Unit('centimeter / second')>

In [13]:
x = Quantity(10., 'km')
x * 2.

<Quantity(20.0, 'kilometer')>

In [14]:
xa = Quantity(np.array((1,2)), 'km')
xa[1] * 2.5

<Quantity(5.0, 'kilometer')>

In [15]:
y = Measurement(10, .1, 'km')
y  

<Measurement(10.00, 0.10, kilometer)>

In [16]:
z = x.plus_minus(.01)
z

<Measurement(10.00, 0.01, kilometer)>

**Warning**, this is not available for numpy.array based quantities !  For this we will use NDDataset described 
below

In [17]:
try:
    za = xa.plus_minus(.01)
except AttributeError as e:
    log.error(e)

'numpy.ndarray' object has no attribute 'strip'


## NDDataset, the main object

NDDataset is a python object, actually a container, which can represent most of your multidimensional spectroscopic data.

For instance, in the following we read data from a series of FTIR experiments, provided  by the OMNIC software:

In [18]:
nd = NDDataset.read_omnic(os.path.join('irdata', 'NH4Y-activation.SPG'))

Note that for this example, we use data stored in a ``test`` directory. For your own usage, you probably have to give the full pathname (see ... for the way to overcome this using `preferences` setting)

### Display dataset information

Several ways are available to display the data we have jsut read and that are now stored in the ``source`` dataset 

* **Printing** them, using the print function of python to get a text version of the `source` information

In [19]:
print(nd)

      name/id: NH4Y-activation.SPG
       author: spectrocat@cf-macbookpro.local
      created: 2019-01-18 17:53:19.508877
last modified: 2019-01-18 17:53:19.508877
  description: Dataset from spg file : NH4Y-activation.SPG
               History of the 1st spectrum: vz0521.spa, Thu Jul 07 06:10:41 2016 (GMT+02:00)
      history: 2019-01-18 17:53:19.499282:read from spg file
               sorted
   data title: Absorbance
   data shape: 55 x 5549
  data values:
         [[   2.057    2.061 ...    2.013    2.012]
          [   2.033    2.037 ...    1.913    1.911]
          ...
          [   1.794    1.791 ...    1.198    1.198]
          [   1.816    1.815 ...    1.240    1.238]] a.u.
 y-coordinate:
               title: Acquisition timestamp (gmt)
                data: [1467831794.000 1467832394.000 ... 1467864197.000 1467864797.000] s
              labels: [[2016-07-06 19:03:14+00:00 2016-07-06 19:13:14+00:00 ... 2016-07-07 04:03:17+00:00 2016-07-07 04:13:17+00:00]
          [vz0466.

* **Displaying html**, inside a jupyter notebook, by just typing the name of the dataset (must be the last instruction of a cell, however!)

In [20]:
nd

NDDataset: [[   2.057,    2.061, ...,    2.013,    2.012],
            [   2.033,    2.037, ...,    1.913,    1.911],
            ...,
            [   1.794,    1.791, ...,    1.198,    1.198],
            [   1.816,    1.815, ...,    1.240,    1.238]] a.u.

### Plotting a dataset

Let's plot first a 1D spectrum (for instance one row of nd)

In [21]:
row = nd[-1]
_ = row.plot()

_ = nd.plot(method='stack') # or nd.plot_stack()

FigureCanvasNbAgg()

FigureCanvasNbAgg()

or as a contour plot: 

In [22]:
_ = nd.plot(method='map')

FigureCanvasNbAgg()

Note that as we plot wavenumbers as abcissa, by convention the coordinates dirtection is reversed.

This can be changed by using the keyword argument `reversed` = `False`.

### Processing a dataset

Some arithmetic can be performed on such dataset. Here is an example where we subtract one reference spectrum to the whole nddataset that we have read above (`nd`).

Lets take, e.g., the last row as reference

In [23]:
ref = nd[-1]
_ = ref.plot() 

FigureCanvasNbAgg()

Now suppress this ref spectrum to all other spectra of the whole dataset

In [24]:
nds = nd - ref  
_ = nds.plot(method='stack')

FigureCanvasNbAgg()

More details on available on available processing and analysis function will be given later in this user guide.


In [25]:
show() # Note : show all plots (only required if the notebook is exported as a script, to make all plots visibles)

## File selector widget

A widget is provided to help with the selection of file names or directory.  

In [26]:
path = general_preferences.datadir
fs = FileSelector(path = path, filters=['spg','scp'])
fs

Intake GUI instance: to get widget to display, you must install ipy/jupyter-widgets, run in a notebook and, in the case of jupyter-lab, install the jlab extension.

After validation of the selection, one can read the path and name of the selected files. 

In [27]:
fs.value, fs.path, fs.fullpath

(None,
 '/Users/spectrocat/Dropbox/spectrochempy/scp_data/testdata/',
 '/Users/spectrocat/Dropbox/spectrochempy/scp_data/testdata/')