In [1]:
%matplotlib inline

In [2]:
#
# ======================================================================================================================
# Copyright (©) 2015-2019 LCS
# Laboratoire Catalyse et Spectrochimie, Caen, France.
# CeCILL-B FREE SOFTWARE LICENSE AGREEMENT
# See full LICENSE agreement in the root directory
# ======================================================================================================================

Solve a linear equation using LSTSQ
-----------------------------------
In this example, we find the least  square solution of a simple linear
equation.


In [3]:
# sphinx_gallery_thumbnail_number = 2

import os
from spectrochempy import *
from spectrochempy import show


<img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAAlw
 SFlzAAAJOgAACToB8GSSSgAAAetpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6
 bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8x
 OTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAg
 eG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMu
 YWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+bWF0cGxvdGxpYiB2ZXJzaW9uIDIuMS4wLCBo
 dHRwOi8vbWF0cGxvdGxpYi5vcmcvPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6
 T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgqNQaNYAAAGiUlE
 QVRIDY1We4xU1Rn/3XPuYx47u8w+hnU38hTcuoUEt/6D2y4RB0ME1BoEd9taJaKh9CFiN7YGp7appUAMNmktMZFoJTYVLVQ0smsy
 26CN0SU1QgsuFAaW3WVmx33N677O6XfuyoIxTXqSO/fec+75fd93vt/3/UbDV0aKSZmCpkFMLz3T9utuu2N+o98aDSMBKVAo89z5
 y+zEz3ZafcCOfvWdlGCalqKn1Bf71CygTd+mf1esSOnpdMpTb+vWpTZuWVfe3jLPa5tzHYNm0T5N0gpdkkHaDBeGBU6d1/t/fyS8
 +/CbqdfUvmsx1PuMgc2bNxv79u1zgd31r+7JH1jbIZKxWRXAcYUQ8IWvBfBXNjEuJWPgMA02NR7C3/pYT9fjdZ3A9tGrWF8YSJHn
 qcDz3y7q2T967PZv+gnYJdd1mEZ+62zGDQV/dQgKhmLzDNOXCEWM3j6eTT5Y3w78dOBKJLR1PQf+4ivPj76UPZnssBN+wbM9Aet/
 AV81Mf1EEULXYfOobvX2WWQk0aoioXwwSmirOlioY0mu8BIouzYl7P8GV3vpqCCEZvlFz769w08oLDWvyKIyL1asSm28d6WfzA97
 ztvvV1kexUMsmhlkULEkuGYmFYC6AvfUrITnwUKl5K79lkjeSSRRTCTbQPd95e1WzMbZSya74XoXAxctCllCnbECMOjZNGRwvzIX
 nD85wbkMmKK+U045Dtdi8Qp+SAxU2GTg2bYlC9224pgvmSb54vkVTBQYyhUt2KjAMyMmPjwRQW5Mh2WKwJhlBh6jVGagFM84wZnQ
 4bpC0Rt4pk1PbSt0NDcxDA5xryosDHWgtbM0DGZDWLSoiDMDYeQnGVrmOThxLozB0RAaahzkJzjKNqcIQBymJFMkOlN8Dqjpg0XY
 Tx5xO/QbmmUrqIjGJznq47TqTaClKYfjp+PInLMwnOdYvtQBZ2XcunQY+VwIo4U4muoFEjVEFE6lQyEUKzHYfgQG9ylCyngU+Cxj
 tOqxCDGHcCsOMCs6iQul5ZiStdATYxjMZXDLTUVwLY8Jey4uOh2IxjwsrP8UXJYxUrkZrghBahzV5iXU6gNkq0Z1EzIsUBUSCV2n
 EOHo0LVxHCpuxabJJdhi5PFnvw5vLXwXIfNZvD/+JNo/X40NegE54sUaazl+UL8XD1x+FB9Ijjt4EQfdGN6J/x131LwIV9ap/AYs
 0x1fz1ZKFbh6A7qKy/By9Dg6G36Ep91vUJJ15Cqr0Z67E8/HzmBrw1OwxWyM+3Mo6BAuSB17oyfx0Oyl2DN0Hqs/70Cx6hBCvESF
 UY1ShWXZZEE7OTAYxZzaPH4TuoiusZvRnunFy2NbiHYuBp2vB66srX4vMEjpRKPxKXmnoQ4+Mn4DPiv8CYcrs3GfNUXJLtM+alSO
 hrMj/KT+wBNW3+E/2liywNO3iSflbaFva/+stGDTxE0E9Sjaox8HBhxpEamzMGSEaFKg+mjEddzDh1MxTDq3YV1kGBsjfwW3S9Cq
 anjmko+ndlb1UR3s6K8JlfphNWq9Ew/7c61T2BB/EbcaNkb8GBaE0tANH7/M34PLdhJDzjIcL9xPbdTG6zyM72Y+wXPHmvB489No
 fm0b5HnbQ9Rgp/7DSSd29AeVvPeNyK6JcYl/yQVi5dBjuGvoV/gaJe47s45QUxrDmcYX0MBsdF7egvXZ7+O0vZA4X8QmOQWjlSK7
 RDz5wIM30gp9UbWcGjXxhzdDu1SiNSpx6kcQB57rPnr/3dlkZarWLnlRq5oPET1dOCIOk4wALib9eeS5iygfhkd09H0DWphB/+gs
 +PcOAS+ssrFmmXXgVfR0de9cpbAJfH3Q1jofW9DZk56dDcVsq9YcsoUMEd1qyLoT3BX1YiyHMJuk97hyjqIoE91t+NcTLeN0ZrfM
 oXatZbu6G0h4VG+ibqq0IJVK6cAjo6serG3vSUezCMct0yQeSOFJSUImqb2qbknUpDqlZxE0QZ+ZUpSlZx79h4Nda6zef9dlk121
 JDjbR5XggPRZlRnS6bRQRtLpn4++cuie/Yvn2svmNxuLw9WCcYIl4fEoTEGiSTUqJdfgU+8ROqf1iMkLzS389YtNPXc/PH8l8ONB
 JZkHD+4JtD04HmVEDWWErmBhzV2/2LB1bemJG6krzv2S6NOHUgtEP0Oif5pE/3fHoruP7N8RiP61GArzSwbUhJJQpXJKiKbfr/3b
 IhKq76sKPUdF9NW/LSqfSn6vjv8C45H/6FSgvZQAAAAASUVORK5CYII='
 style='height:25px; border-radius:12px; display: inline-block; float: left; vertical-align: middle'> 
 
 
 
    SpectroChemPy's API - v.0.1a10.dev22+g19081ce5.d20190220 © Copyright 2014-2019 - A.Travert & C.Fernandez @ LCS

Let's take a similar example to the one given in the `numpy.linalg`
documentation

We have some noisy data that represent the distance `d` traveled by some
objects versus time `t`:

In [4]:
t = NDDataset(data=[0, 1, 2, 3],
                  title='time',
                  units='hour')

d = NDDataset(data=[-1, 0.2, 0.9, 2.1],
                  coords =[t],
                  title='distance',
                  units='kilometer')

Here is a plot of these data-points:

In [5]:
_ = d.plot_scatter(markersize=7, mfc='red')

FigureCanvasNbAgg()

We want to fit a line through these data-points of equation

.. math::

   d = v.t + d_0

By examining the coefficients, we see that the line should have a
gradient of roughly 1 km/h and cut the y-axis at, more or less, -1 km.

Using LSTSQ, the solution is found very easily:

In [6]:
lst = LSTSQ(t, d)

v, d0 = lst.transform()
print('speed : {:.3fK},  d0 : {:.3fK}'.format(v, d0))


speed : 1.000 km.hr^-1,  d0 : -0.950 km


Final plot

In [7]:
d.plot_scatter(markersize=10,
               mfc='red', mec='black',
               label='Original data', suptitle='Least-square fitting '
                                                 'example')
dfit = lst.inverse_transform()

dfit.plot_pen(clear=False, color='g', label='Fitted line', legend=True)


FigureCanvasNbAgg()

Note: The same result can be obtained directly using `d` as a single
parameter on LSTSQ (as `t` is the `x` coordinate axis!)

In [8]:
lst = LSTSQ(d)

v, d0 = lst.transform()
print('speed : {:.3fK},  d0 : {:.3fK}'.format(v, d0))

speed : 1.000 km.hr^-1,  d0 : -0.950 km


In [50]:
import numpy as np
npoints = 20
slope = 2
offset = 3
x = np.arange(npoints)
y1 = slope * x + offset + np.random.normal(size=npoints)
y2 = np.vstack([y1, 
               2* slope * x + offset + np.random.normal(size=npoints)]).T

In [51]:
import matplotlib.pyplot as plt # So we can plot the resulting fit
A = np.vstack([x,np.ones(npoints)]).T
print(A, x, y1)
m, c = np.linalg.lstsq(A, y1)[0] # Don't care about residuals right now
#fig = plt.figure()
#ax  = fig.add_subplot(111)
#plt.plot(x, y, 'bo', label="Data")
#plt.plot(x, m*x+c, 'r--',label="Least Squares")
#plt.show()
M, R, _, _ = np.linalg.lstsq(A, y1)
print(M, R)
print(A.shape, M.shape, y1.shape)
np.sum((np.dot(A,M) - y1)**2, axis=0)

[[   0.000    1.000]
 [   1.000    1.000]
 ...
 [  18.000    1.000]
 [  19.000    1.000]] [       0        1 ...       18       19] [   2.253    4.791 ...   36.185   40.864]
[   2.017    2.651] [  15.787]
(20, 2) (2,) (20,)


15.786896402438153

In [52]:
import matplotlib.pyplot as plt # So we can plot the resulting fit
A = np.vstack([x,np.ones(npoints)]).T
print(A, x, y2)
m, c = np.linalg.lstsq(A, y2)[0] # Don't care about residuals right now
#fig = plt.figure()
#ax  = fig.add_subplot(111)
#plt.plot(x, y, 'bo', label="Data")
#plt.plot(x, m*x+c, 'r--',label="Least Squares")
#plt.show()
M, R, _, _ = np.linalg.lstsq(A, y2)
print(M, R)
print(A.shape, M.shape, y.shape)
np.sum((np.dot(A,M) - y2)**2, axis=0)

[[   0.000    1.000]
 [   1.000    1.000]
 ...
 [  18.000    1.000]
 [  19.000    1.000]] [       0        1 ...       18       19] [[   2.253    2.717]
 [   4.791    7.358]
 ...
 [  36.185   77.030]
 [  40.864   80.898]]
[[   2.017    4.010]
 [   2.651    3.049]] [  15.787   26.730]
(20, 2) (2, 2) (20, 2)


array([  15.787,   26.730])

In [11]:
S = np.arange(40).reshape(10,4)
S

array([[       0,        1,        2,        3],
       [       4,        5,        6,        7],
       ...,
       [      32,       33,       34,       35],
       [      36,       37,       38,       39]])

In [12]:
X = np.arange(30).reshape(10,3)
X

array([[       0,        1,        2],
       [       3,        4,        5],
       ...,
       [      24,       25,       26],
       [      27,       28,       29]])

In [13]:
np.linalg.lstsq(S, X)[0]

array([[   0.525,    0.225,   -0.075],
       [   0.300,    0.200,    0.100],
       [   0.075,    0.175,    0.275],
       [  -0.150,    0.150,    0.450]])

In [14]:
Sd = NDDataset(S)
Xd = NDDataset(X)
lst = LSTSQ(Sd, Xd)

v, d0 = lst.transform()

ValueError: all the input array dimensions except for the concatenation axis must match exactly